apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nexus-proxy-secret
  namespace: nordmart-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBrETIdLUEWVtwauj4/HzH0sELpcWBm+yCr46ZjpKE7gFryMRl05+A7wRRxBsR4zME88Sm89e/n/Nr/Z64z1SNybt5Qcllhcp59CH3wkndr2Y1w3+/cN2AjdoH7zYAcfk678/q6WC/itDmExnlUSoO3eApHB+ip6kML7FHEw0UsxTumGsiCjCzqor1zn747O46yiJ4T+B+Uf5x5vE5eh5yXKLowdWJb9mo60zNEao10bw+dVTyeaXe46j34ovQpBBAN/o8pkgfEkZ58uhW+D6C8S0iA7MVLJ0aos7ZGIjeNNw/mLbAjoqxXOSXQiQvOTnjhw/TpJk9bXh9Dryu1ZjHJs98qxg9lyctQun8N6Q7b5QWE0aBDZkF73jvfXMYmpWrsne/rQUm0/ZwWmpkiYM1viMqVLqp3XthVymnHaEiP7+qs40u+WtrOCh161IRk9FM4giqYF43mH/Jv3SolsbhZnlOg9jTamb0JoDwIiNl92oVvnX5hI7DheNrWByoQbSQkGkP53SAXCzfMXaftEdq6IKAp+RHp7tJ+H808gCy1foApjoXe+wG+b8amGiT0/fDOcXFoe8zxlEqCUY2ZjBh1hD5CvYdSel+/qCIeIvGY4cykFxwcY9xKDChX9D/wHpgMEZISwOasrVLXrGDr1lR0cH9Uugvtrii6cPO0oCuSFNMJDsYi5oOsfdYDh8BzPjcO10XK1bWD9SRvprw5f2ym2EW/lCxNSZyXt44DiliHqdH/ofEF8FMsAnm5Mf61kKwknMrxY54BOUfHFMSHYcbtkg6qotqtWQbjU85i5rVMZhbvtyCkGnJX/0r/i7UB0IJZy5NkS36/SDnnh2hphOq0jetaslxyg0YMKSfxnbahuyhLuskdcCD8J+xDEMV4jCnlRZMq6kb5cGvj7MvRNY+ZBeMcTZ2/8LNzTzUPBlNQZVVnOvBoYGql2VaiezdjOUU=
  template:
    metadata:
      name: nexus-proxy-secret
      namespace: nordmart-dev
    type: kubernetes.io/dockerconfigjson

