---
# Source: application/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory
    appVersion: "v0.0.16"
    group: com.stakater
    provider: stakater
    team: nordmart
    chart: "application-0.0.29"
    release: "stakater-nordmart-inventory"
    heritage: "Helm"
  name: inventory
spec:
  selector:
    app: inventory
  ports:
    - name: https
      port: 8080
      targetPort: 8080
---
# Source: application/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inventory
    appVersion: "v0.0.16"
    group: com.stakater
    provider: stakater
    team: nordmart
    chart: "application-0.0.29"
    release: "stakater-nordmart-inventory"
    heritage: "Helm"
  annotations: 
    reloader.stakater.com/auto: "true"
  name: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: "docker.io/stakater/stakater-nordmart-inventory:v0.0.16"
        imagePullPolicy: IfNotPresent
        env:
          - name: JAEGER_ENDPOINT
            value: http://jaeger-collector.istio-system:14268/api/traces
          - name: POSTGRESQL_HOST
            value: stakater-nordmart-inventory-postgresql-svc
          - name: DB_NAME
            value: inventory
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: inventory-postgresql-secret          
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 15
          httpGet:
            path: /actuator/health
            port: 8080
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 15
          httpGet:
            path: /actuator/health
            port: 8080
        resources:
          limits:
            memory: 256Mi
            cpu: 0.5
          requests:
            memory: 128Mi
            cpu: 0.1
      serviceAccountName: inventory
