---
# Source: helm/charts/application/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: stakater-nordmart-promotion-1
    appVersion: "SNAPSHOT-PR-1-d7483572"
    group: com.stakater.platform
    provider: stakater
    team: stakater
    chart: "application-0.0.29"
    release: "stakater-nordmart-promotion"
    heritage: "Helm"
  name: stakater-nordmart-promotion-1
---
# Source: helm/charts/mysql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promotion-sql
  labels:
    app: mysql
    chart: mysql-7.1.0
    release: "stakater-nordmart-promotion"
    heritage: "Helm"
secrets:
  - name: promotion-sql-secret
---
# Source: helm/charts/mysql/templates/master-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: promotion-sql-master
  labels:
    app: mysql
    chart: mysql-7.1.0
    release: stakater-nordmart-promotion
    heritage: Helm
    component: master
data:
  my.cnf: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/plugin
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    
    [client]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/plugin
    
    [manager]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
---
# Source: helm/charts/application/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stakater-nordmart-promotion-1
    appVersion: "SNAPSHOT-PR-1-d7483572"
    group: com.stakater.platform
    provider: stakater
    team: stakater
    chart: "application-0.0.29"
    release: "stakater-nordmart-promotion"
    heritage: "Helm"
  name: stakater-nordmart-promotion-1
spec:
  selector:
    app: stakater-nordmart-promotion-1
  ports:
    - name: https
      port: 8080
      targetPort: 8080
---
# Source: helm/charts/mysql/templates/master-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: promotion-sql
  labels:
    app: mysql
    chart: mysql-7.1.0
    release: stakater-nordmart-promotion
    heritage: Helm
    component: master
  annotations:
    prometheus.io/port: '9104'
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      nodePort: null
  selector:
    app: mysql
    release: stakater-nordmart-promotion
    component: master
---
# Source: helm/charts/application/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stakater-nordmart-promotion-1
    appVersion: "SNAPSHOT-PR-1-d7483572"
    group: com.stakater.platform
    provider: stakater
    team: stakater
    chart: "application-0.0.29"
    release: "stakater-nordmart-promotion"
    heritage: "Helm"
    appCategory: backend
  annotations: 
    reloader.stakater.com/auto: "true"
  name: stakater-nordmart-promotion-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stakater-nordmart-promotion-1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stakater-nordmart-promotion-1
    spec:      
      imagePullSecrets:
      - name: nexus-creds
      containers:
      - name: stakater-nordmart-promotion-1
        image: "nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-promotion:SNAPSHOT-PR-1-d7483572"
        imagePullPolicy: IfNotPresent
        env:
          - name: SQL_HOST
            value: promotion-sql-secret
          - name: SQL_USER
            value: root
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mysql-root-password
                name: promotion-sql-secret          
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 90
          httpGet:
            path: /health
            port: 8080
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 90
          httpGet:
            path: /health
            port: 8080
        resources:
          limits:
            memory: 1Gi
            cpu: 0.5
          requests:
            memory: 128Mi
            cpu: 0.1
      serviceAccountName: stakater-nordmart-promotion-1
---
# Source: helm/charts/mysql/templates/master-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: promotion-sql-master
  labels:
    app: mysql
    chart: mysql-7.1.0
    release: stakater-nordmart-promotion
    heritage: Helm
    component: master
spec:
  selector:
    matchLabels:
      app: mysql
      release: stakater-nordmart-promotion
      component: master
  serviceName: promotion-sql-master
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
        chart: mysql-7.1.0
        release: stakater-nordmart-promotion
        heritage: Helm
        component: master
    spec:      
      imagePullSecrets:
        - name: nexus-proxy-secret
      serviceAccountName: promotion-sql
      containers:
        - name: mysql
          image: nexus-docker-proxy-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/bitnami/mysql:8.0.22-debian-10-r23
          imagePullPolicy: "IfNotPresent"
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: promotion-sql-secret
                  key: mysql-root-password
            - name: MYSQL_USER
              value: "nordman"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: promotion-sql-secret
                  key: mysql-password
            - name: MYSQL_DATABASE
              value: "nordman-promotion"
          ports:
            - name: mysql
              containerPort: 3306
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  password_aux="${MYSQL_ROOT_PASSWORD:-}"
                  if [ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]; then
                      password_aux=$(cat $MYSQL_ROOT_PASSWORD_FILE)
                  fi
                  mysqladmin status -uroot -p$password_aux
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  password_aux="${MYSQL_ROOT_PASSWORD:-}"
                  if [ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]; then
                      password_aux=$(cat $MYSQL_ROOT_PASSWORD_FILE)
                  fi
                  mysqladmin status -uroot -p$password_aux
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: data
              mountPath: /bitnami/mysql
            - name: config
              mountPath: /opt/bitnami/mysql/conf/my.cnf
              subPath: my.cnf
      volumes:
        - name: config
          configMap:
            name: promotion-sql-master
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: mysql
          component: master
          release: stakater-nordmart-promotion
          heritage: Helm
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
---
# Source: helm/templates/secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: promotion-sql-secret
spec:
  encryptedData:
    mysql-password: AgCav63lxp6BVsXPFUtu4oIyex6kSkp+ssxZPzDJp60qABTROLhigI/zcE28lepgVy4CqL42zfZxBmY9XTf4ScR/TeAG90lAqBgf+xxnpgaYpmE5TjX0hLdNCn2VkEiioshwMF8W7coaArHrcOjxLuQIcVfbWNQa4XVEIvE/PyNyb7INoVFMVJHTvT7BSgucEnS5zyuuNZf1yZyFf0OYoOT9svBopgFL/kVbTsswA9vZPI391FiQ2S8/ovKmNlvEagyLrNdD/DYytx40XFDn5omVPJiF7bzVv300SkvzrRUEYfMIblBrCzRQwowYPVFdUyJi3w6YE7CiF0zUm+nXFBU6d9iUCRzCiCl6XIBcEsoqz00zd+rOOVYW+vS8q9W1MHgCOXFgoITnoMxjcJ69LGXRGm38KxcDqWXnhDvXTR5MoA5G5B5vJoaeaALWCQGRvoBmYgKnFGl77mPPm0VLMfbMTvEQYtag6c0z8xPVZ4xzdTKr8+4n7+Opm3bqiipR7Ya6E94CKbfWLEclgqbfcDKLw1TyIZ5RuEkKOqmogrg5H2Tg2YpiidcDxj1ty2iPidOWOerrfZebyZSkrBNFln/W6agfJU8MBf335waO679kAXlkTMkvVfLrIRoh1ZtF7GkkvY3yTj9UmMJuk5x3wppYoBLUEWPGbyFFnMwZvpADKYfpOV4oCnsbmoruwGMXh0WzjxT11Ckq
    mysql-root-password: AgBpjdRKVselLnh0b1mJjSFyz+8Z6b87pV7hys9uzC6v70Oyo9ijktKiJUTs/rapUhyGZ06Vn7lVXqM+qsirOZTs/mO307wy7w0oekT1FLDjN8B23Dvw3X28Iim/FTa5QLJGRQtam/Gj9dzh880wLWx09DbgTgrqXkkPUwls3k2ByzfE18AdBBq1O1W8cMPXEWmijbvtdvS6D1Ek3KAOW1pySxtX9bkuFD8jZxx2sPwsCnDzw7ht5NPMfDoofoX8lAFr02ly94p2giBAGnH3l4BlOM5KPNDQ1nxmyz7x84vUnADtOn0Txi03Zd5aAzCq+U6MNec2PQ2k3v+GArCTvOc/Zvq0oh+2GiXqFUMk9TybdxMtaX4GVzAoo24TdOIl3Wg8/ARNkzUMtivIhcHsRO92SRop0NG9vRS3vUZoPXRpt5csG4L5uOcArrRX/4pUS6hfmYFMQJeKBPaUnXhfnf5YWY9lE5juIST3Y3pK6t3oziMeZwocSCoNbS8nsPJBq/9dWB3VCYQnjtr13WQbGIKnfbAiClz8AbujETNfBzf1MUzb0ILgPpzrhMmy92uVyZo4YaN9EAR1V0WfM8iaH+KdZjPBLAjDOFeXf00/ayOy70L72znzk/OWjvgDZ2LFbCjAfBCHtoWfN85tMcMhNgA/7KcB/77Ebt7L4jdTKhgg6PNsVN3TtTj1fEonir/rFk2vrxtUVAdXGovJpdY=
    mysql-username: AgAGnQHVtbocyXeHbijk/LNG2EjSKGYGsRAdUmv2flchbi75u22HNVfocQoL57rZxdjdyYk2ep9Gx9XtAN1buZFV45e/E9kcj2Gvk4mI/jVX8+wdC1KFxC5H4Wag3pycaYDSG0Y1jjrwlCL1E772bU4NG4A7eCTZZejMmSxM3D9lXWRcgdN8P7um/bAW0E8jm5lLpX9zHLOfDSxBsNSOvse7VKE2xfLvupRYDYIqW3zR9yinTYoZm5pfQ+fOV0z80R1Bn19OrjUx3WDuxHK8FW9Uud1CBrK2kzEp6s3llydFEUBFyq6cRos8N5yRLQaiBwtNQL7zrqAwwIOuKpyc3NqSjQrrR9NVdi5OZ3q7LuNrw1QfnVPAb3KxjyR6mUnzRW09+2JVsOVM2hJ2uq6iBSRuwBiefc8Rs/vvyS3+i3vfZs0EIxcAYE1wEo4MC9euUMyHLRa95eN4iGSRqwExK/fUu1S0+MNWcITK0HG5M3LGSN0gkKmWIR9HgpluEcaTK2S5dBQDLYb99bgD5finCr5UsehRCpAedwcapxcbHUR7KiaNUF8PU4tY/KWE7fTLtlDndrxkW/fySX7TRaaL0jUR+weun6pkBHP7PbevwNP4zihhQTNV7SgBgT2wH0XR3br3P/WqpBO2b6Er8gUQlvH/LW3e43+LZ98tmQgmonu3A1lMMdqcBI5/3ix9/IAdK6tIGfbL949l
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: promotion-sql-secret
      namespace: nordmart-dev
