---
# Source: helm/charts/application/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: stakater-nordmart-cart-40
    appVersion: "SNAPSHOT-PR-40-a014eb9b"
    group: com.stakater.platform
    provider: stakater
    team: stakater
    chart: "application-0.0.29"
    release: "stakater-nordmart-cart"
    heritage: "Helm"
  name: stakater-nordmart-cart-40
---
# Source: helm/charts/application/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stakater-nordmart-cart-40
    appVersion: "SNAPSHOT-PR-40-a014eb9b"
    group: com.stakater.platform
    provider: stakater
    team: stakater
    chart: "application-0.0.29"
    release: "stakater-nordmart-cart"
    heritage: "Helm"
  name: stakater-nordmart-cart-40
spec:
  selector:
    app: stakater-nordmart-cart-40
  ports:
    - name: https
      port: 8080
      targetPort: 8080
---
# Source: helm/charts/application/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stakater-nordmart-cart-40
    appVersion: "SNAPSHOT-PR-40-a014eb9b"
    group: com.stakater.platform
    provider: stakater
    team: stakater
    chart: "application-0.0.29"
    release: "stakater-nordmart-cart"
    heritage: "Helm"
    appCategory: backend
  annotations: 
    reloader.stakater.com/auto: "true"
  name: stakater-nordmart-cart-40
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stakater-nordmart-cart-40
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stakater-nordmart-cart-40
    spec:
      containers:
      - name: stakater-nordmart-cart-40
        image: "nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-cart:SNAPSHOT-PR-40-a014eb9b"
        imagePullPolicy: IfNotPresent
        env:
          - name: CATALOG_ENDPOINT
            value: catalog:8080
          - name: KEYCLOAK_REALM
            value: nordmart
          - name: KEYCLOAK_URL
            value: https://keycloak-NAMESPACE.DOMAIN/auth/
          - name: KEYCLOAK_CLIENT_BACKEND
            value: stakater-nordmart-backend
          - name: KEYCLOAK_CLIENT_SECRET_KEY
            value: 7672aea2-81ff-4aa2-affe-daf3bad10334
          - name: JAEGER_ENDPOINT
            value: http://jaeger-collector.istio-system:14268/api/traces          
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /health
            port: 8080
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 10
          httpGet:
            path: /health
            port: 8080
        resources:
          limits:
            memory: 256Mi
            cpu: 0.5
          requests:
            memory: 128Mi
            cpu: 0.1
      serviceAccountName: stakater-nordmart-cart-40
---
# Source: helm/templates/secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgressql
spec:
  encryptedData:
    postgresql-password: AgCgOPKtnDQxqyMXJ9nXBVSLWe29cpWNXwidLbBmoMCU4aDarHJEv+2rJcUIgIwC93qJ/xukp7Aw0x2Gk0AvsDl8jbzYGbb76h8+NzvdkdHCG8+Slm4fHYfax94nR00VdkRKTvJhW2JUgkMAU/CtuKEeCqbTcF5moXWjTLFSzxtDq7u/JY1iioQLltDDQ7pAd2Klo32gzEXkTuaO/xslOThVpNFWjYwwsUkQgm0SYy2CaOL8EKhbV/wtYDVjMOma6yTbPF1FI54cb2FC4CIjyFgIgh3WqddBahcegyy3AOAN+NX8vy3o9FjU4/XvJ/eSCAn8rB2+wyvhCVIUpriA3384Zf4CArFZg/NOuRbtnX7843z1FIPRkrqcuUeni8Ilh5hX6GMqbdSoa9H7SKgo33X2MzoNE4mvf1KacTFopX7fGSs06aYtim8dTTEERnDWeT+KKS2F3r36Wb04RHx2+cO+TKt8+4h633fNVtUYTOpxYgmGadpYQaKY2HJr+LXcBOVmeD3IflMSRjy7q3yamnoXQhT4uyBxgM64lFmP1WdoGeNKqiXgEcfbs2pYLdMrYi2YLYHjgPAHgKwQ+qIf6zeilUIw3mH2Y9P96ru3tYcnlOv1OuCOrVS2bwE7MTXoHO1aIWNmJUbQba5VT09hsQO6TEBG7+LMGiLRVXRI9Ch3jomfP1EF+N9PB9/mgNIvM/tEkgtzKOIiXhLbmQ==
    postgresql-postgres-password: AgATl6KsgGc3xRYT2VWVHRbghlhEVpoF3v1lwcC271mxY1nRbhgzEJGYjU76DMb60D2ZvN6HsbOEeoBSBUSTrpXDYDU7VEck39+yoN6AJmiGJebUhlHfxtzwfm7KrpVTTDKJou9jXibQFOhnqmc6pkEurq5nwHQv26oWLGGy/IgR7ykYTIPKAGgyJsPpgT1/hJ+jYbKBMaI6RtdUJ9reZvOJAXfrx0VGKj1ZML053uc5s+Vnv2z0xo/x+EtGgerneUKeI8EIfizBy5eg6jxmgosuXCttOtoxMd7OhqfEp5Phq2YrvfO6Hi0rMvh7/DpOsEdIF/Mw4cKJWqfvX98oQ+9KytDUNajvssplc2TGsUZPGwWHt5KY/aEpLO2F+YK3unv8fJrSjRtXqhtKpvDHHlYAhLtV5/n8zMS6MNNDDOZsECbn7aFA9R070p6N7HLw1Xkeob0GjPuzq1aLts0dDTK3Q3T1bQn4RztuyryPyFP35ricY0rRblLK6KjRAeIrXLymQJV24IYNMGaP52ipftST9B6XUWQTHbTN+8Wgyso6Qrdkp0I14FCcz9Sqmpu8Q9RZe/gjUylvCQSMi60fzmmE5Gs6Lrl/77tFLCIBhZnsiF6s9vnDggSYuTlYa18nr5ollAp72Z3NfMI89ZUEp+ygAzXK0xmyL2jsinTuAJi2WSopk5DqDZJJ69BQEN27l5MIdQKjUaIKFaXcQI2K
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgressql
